WITH WT_T01 AS (
    SELECT FOOD_TYPE
         , MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT T01.FOOD_TYPE
     , T01.REST_ID
     , T01.REST_NAME
     , T01.FAVORITES
FROM REST_INFO T01
INNER JOIN WT_T01 T02 ON T01.FOOD_TYPE = T02.FOOD_TYPE
    AND T01.FAVORITES = T02.FAVORITES
ORDER BY FOOD_TYPE DESC
;