-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (
    SELECT ROW_NUMBER() OVER(ORDER BY AO.DATETIME - AI.DATETIME DESC) AS RN
        , AI.*    
    FROM ANIMAL_INS AI
    INNER JOIN ANIMAL_OUTS AO
        ON AI.ANIMAL_ID = AO.ANIMAL_ID
)
WHERE RN < 3
ORDER BY DATETIME DESC
;