-- 코드를 입력하세요
SELECT T01.FLAVOR
FROM FIRST_HALF T01-- 상반기 주문 정보
INNER JOIN ICECREAM_INFO T02-- 아이스크림 성분
    ON T01.FLAVOR = T02.FLAVOR
WHERE 1=1
    AND T01.TOTAL_ORDER > 3000
    AND T02.INGREDIENT_TYPE = 'fruit_based' --주 성분 fruit_based: 과일
ORDER BY T01.TOTAL_ORDER DESC
;