-- 코드를 입력하세요
SELECT '/home/grep/src/' || T02.board_id || '/' || T02.FILE_ID || FILE_NAME || FILE_EXT AS FILE_PATH

 -- /home/grep/src/
FROM USED_GOODS_BOARD T01
INNER JOIN USED_GOODS_FILE T02
    ON T01.BOARD_ID = T02.BOARD_ID
WHERE VIEWS = (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
ORDER BY T02.FILE_ID DESC
