-- 코드를 입력하세요
SELECT T01.CATEGORY AS CATEGORY
     , SUM(SALES) AS TOTAL_SALES
     -- , TOTAL_SALES
FROM BOOK T01
INNER JOIN BOOK_SALES T02 ON T01.BOOK_ID = T02.BOOK_ID
WHERE TO_CHAR(T02.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY T01.CATEGORY
ORDER BY CATEGORY