-- 코드를 입력하세요

-- REPLY_ID, WRITER_ID, CONTENTS, CREATED_DATE
-- FROM USED_GOODS_REPLY 
-- ORDER BY CREATED_DATE ASC

SELECT T01.TITLE
     , T01.BOARD_ID
     , T02.REPLY_ID
     , T02.WRITER_ID
     , T02.CONTENTS
     , TO_CHAR(T02.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD T01
INNER JOIN USED_GOODS_REPLY T02
    ON T01.BOARD_ID = T02.BOARD_ID
WHERE TO_CHAR(T01.CREATED_DATE, 'YYYYMM') = '202210'
ORDER BY CREATED_DATE, TITLE
;

