-- 코드를 입력하세요
SELECT DISTINCT T01.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR T01
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY T02
    ON T01.CAR_ID = T02.CAR_ID
    AND TO_CHAR(START_DATE, 'MM') = '10'
WHERE T01.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC
;