name: Move LeetCode Solutions

on:
  workflow_dispatch:  # 수동 실행 옵션 유지
  push:
    paths:
      - '[0-9][0-9][0-9][0-9]-*/**'  # LeetHub가 생성하는 폴더 패턴

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리 가져오기 (rebase/merge 충돌 최소화)

      - name: Move LeetCode solutions
        run: |
          echo "Current directory contents:"
          ls -la
          
          mkdir -p leetcode

          echo "Changed files in this push:"
          git diff --name-only HEAD^ HEAD || true
          
          found=0
          for d in [0-9][0-9][0-9][0-9]-*; do
            if [ -d "$d" ]; then
              echo "Moving directory: $d"
              mv "$d" "leetcode/" && found=1
            fi
          done
          
          if [ $found -eq 0 ]; then
            echo "No matching directories found to move"
          fi

      - name: Commit & Push changes
        run: |
          if git status --porcelain | grep .; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m "chore: Move leetcode solutions to leetcode folder"
            
            # 원격 변경사항 병합 (충돌 시 원격 우선)
            git pull origin master --no-rebase --strategy-option=theirs
            
            git push
          else
            echo "No changes to commit"
          fi
